package app.podara.util

object Strings {
    private var currentLanguage: String = Settings.getLanguage()

    fun updateLanguage(language: String) {
        currentLanguage = language
    }

    private val en = mapOf(
        "app_name" to "Podara",
        "nav_home" to "Home",
        "nav_discover" to "Discover",
        "nav_subscriptions" to "Subscriptions",
        "nav_history" to "History",
        "nav_settings" to "Settings",
        "nav_back" to "Back",
        "home_title" to "Podara",
        "home_empty" to "No podcasts yet",
        "home_empty_hint" to "Add one to get started!",
        "home_add_podcast" to "Add Podcast",
        "discover_title" to "Discover",
        "discover_search_hint" to "Search podcasts",
        "discover_search" to "Search",
        "discover_add" to "Add Podcast",
        "discover_added" to "Added",
        "history_title" to "History",
        "history_subtitle" to "Your listening history",
        "history_search_placeholder" to "Search history...",
        "history_today" to "Today",
        "history_yesterday" to "Yesterday",
        "history_this_week" to "This Week",
        "history_earlier" to "Earlier",
        "history_count" to "%1\$d episodes",
        "history_empty" to "No history yet",
        "history_empty_hint" to "Episodes you play will appear here",
        "history_clear" to "Clear History",
        "history_clear_confirm" to "Are you sure you want to clear all history?",
        "history_clear_action" to "Clear",
        "settings_title" to "Settings",
        "settings_data" to "Data",
        "settings_export_opml" to "Export OPML",
        "settings_export_opml_desc" to "Export your podcast subscriptions as OPML",
        "settings_export" to "Export",
        "settings_import_opml" to "Import OPML",
        "settings_import_opml_desc" to "Import podcast subscriptions from OPML file",
        "settings_import" to "Import",
        "settings_downloads" to "Downloads",
        "settings_download_location" to "Download Location",
        "settings_download_speed_limit" to "Download Speed Limit",
        "settings_download_speed_unlimited" to "Unlimited",
        "settings_download_speed_hint" to "Enter the maximum download speed per task (0 for unlimited):",
        "settings_download_speed_error" to "Please enter a non-negative integer",
        "settings_download_speed_unit" to "KB/s",
        "settings_change" to "Change",
        "settings_reset_default" to "Reset to Default",
        "settings_language" to "Language",
        "settings_about" to "About",
        "settings_version" to "Version %1\$s",
        "player_play" to "Play",
        "player_pause" to "Pause",
        "player_queue" to "Queue",
        "player_close" to "Close",
        "player_no_playback" to "No playback",
        "player_now_playing" to "Now Playing",
        "player_seek_back" to "Seek Back",
        "player_seek_forward" to "Seek Forward",
        "player_previous" to "Previous",
        "player_next" to "Next",
        "player_queue_count" to "Queue (%1\$d)",
        "player_queue_empty" to "Queue is empty",
        "player_select" to "Select",
        "player_remove" to "Remove",
        "player_delete" to "Delete",
        "player_sleep_timer" to "Sleep Timer",
        "player_sleep_timer_active" to "Active: %1\$d min",
        "player_cancel_timer" to "Cancel Timer",
        "player_minutes" to "%1\$d minutes",
        "player_timer" to "Timer",
        "player_mute" to "Mute",
        "player_unmute" to "Unmute",
        "episode_new" to "NEW",
        "episode_download" to "Download",
        "episode_downloaded" to "Downloaded",
        "episode_add_to_queue" to "Add to Queue",
        "dialog_ok" to "OK",
        "dialog_cancel" to "Cancel",
        "dialog_close" to "Close",
        "dialog_copy_to_clipboard" to "Copy to Clipboard",
        "opml_export_title" to "Export OPML",
        "opml_export_copy_hint" to "Copy the OPML content below:",
        "opml_export_copied" to "OPML copied to clipboard!",
        "opml_import_title" to "Import Complete",
        "opml_import_added" to "Added: %1\$d podcasts",
        "opml_import_skipped" to "Skipped (duplicates): %1\$d",
        "opml_import_failed" to "Failed: %1\$d",
        "opml_import_error" to "Import Failed",
        "error_loading" to "Failed to load: %1\$s",
        "error_adding_podcast" to "Failed to add: %1\$s",
        "add_podcast_hint" to "Enter the RSS feed URL of the podcast:",
        "add_podcast_rss_label" to "RSS Feed URL",
        "add_podcast_rss_placeholder" to "https://example.com/feed.xml",
        "discover_featured" to "FEATURED",
        "discover_latest_episode" to "Latest Episode",
        "discover_more" to "More",
        "discover_new_episodes" to "Trending Podcasts",
        "discover_next" to "Next",
        "discover_previous" to "Previous",
        "discover_results" to "Results",
        "discover_search_clear" to "Clear",
        "discover_search_placeholder" to "Search podcasts, episodes, topics...",
        "discover_show_all" to "Show All",
        "discover_subtitle" to "Curated podcasts, handpicked for you.",
        "discover_trending" to "Trending This Week",
        "nav_downloads" to "Downloads",
        "downloads_empty" to "No downloads yet",
        "downloads_empty_hint" to "Episodes you download will appear here",
        "downloads_subtitle" to "Manage your downloaded episodes and active tasks",
        "downloads_in_progress" to "In Progress",
        "downloads_completed" to "Completed",
        "downloads_summary_downloads" to "%1\$d episodes",
        "downloads_summary_storage" to "Storage: %1\$s",
        "downloads_summary_path" to "Location",
        "downloads_pause" to "Pause",
        "downloads_resume" to "Resume",
        "downloads_cancel" to "Cancel",
        "downloads_status_paused" to "Paused",
        "downloads_status_failed" to "Failed",
        "downloads_retry" to "Retry",
        "downloads_delete" to "Delete",
        "downloads_delete_confirm" to "Delete this downloaded episode?",
        "downloads_delete_podcast_confirm" to "Delete all downloads for \"%1\$s\"?",
        "downloads_delete_all" to "Delete All",
        "downloads_file_missing" to "File not found",
        "downloads_open_folder" to "Open Folder",
        "nav_episodes" to "Episodes",
        "nav_shows" to "Shows",
        "player_expand" to "Expand",
        "podcast_already_exists" to "Podcast already exists: %1\$s",
        "podcast_no_episodes" to "No episodes available",
        "podcast_retry" to "Retry",
        "loading_episodes" to "Loading episodes…",
        "queue_clear" to "Clear",
        "queue_title" to "Up Next",
        "search_failed" to "Search failed: %1\$s",
        "settings_about_desc" to "Podara - Podcast Player",
        "titlebar_close" to "Close",
        "titlebar_maximize" to "Maximize",
        "titlebar_minimize" to "Minimize",
        "home_edit" to "Edit",
        "home_cancel" to "Cancel",
        "home_select_all" to "Select All",
        "home_delete_selected" to "Delete Selected",
        "home_selected_count" to "Selected %1\$d",
        "unsubscribe" to "Unsubscribe",
        "unsubscribe_confirm" to "Are you sure you want to unsubscribe from \"%1\$s\"?",
        "batch_unsubscribe" to "Batch Unsubscribe",
        "batch_unsubscribe_confirm" to "Are you sure you want to unsubscribe from the selected %1\$d podcasts?",
        "player_follow" to "Follow",
        "player_following" to "Following",
        "player_episode_notes" to "Episode Notes",
        "player_show_more" to "Show more",
        "player_show_less" to "Show less",
        "player_you_might_also_like" to "You might also like",
        "player_rewind_15" to "Rewind 15s",
        "player_forward_30" to "Forward 30s",
        "home_subscriptions" to "Subscriptions",
        "home_subscriptions_desc" to "The podcasts you follow and never miss an episode.",
        "home_search_placeholder" to "Search my podcasts...",
        "home_manage" to "Manage",
        "home_sort" to "Sort",
        "home_subscription_count" to "%1\$d Subscriptions",
        "home_episode_count" to "%1\$d episodes",
        "home_new_badge" to "New",
        "home_new_count" to "%1\$d new",
        "home_sort_title" to "Sort by",
        "home_sort_name_asc" to "Name A-Z",
        "home_sort_name_desc" to "Name Z-A",
        "home_sort_recent_update" to "Recent Update",
        "home_sort_recent_listen" to "Recently Listened",
        // ── System Tray ──
        "tray_show" to "Show Podara",
        "tray_hide" to "Hide Podara",
        "tray_play" to "Play",
        "tray_pause" to "Pause",
        "tray_previous" to "Previous",
        "tray_next" to "Next",
        "tray_quit" to "Quit",
        // ── Close Dialog ──
        "close_dialog_title" to "Minimize to Tray?",
        "close_dialog_message" to "What happens when you close the window?",
        "close_action_quit" to "Quit the app",
        "close_action_minimize" to "Minimize to tray, keep playing",
        "close_remember" to "Remember my choice",
        // ── Close Behavior Settings ──
        "settings_close_behavior" to "Close Behavior",
        "settings_close_behavior_desc" to "Choose what happens when you close the window",
        "settings_close_quit" to "Quit the app",
        "settings_close_minimize_tray" to "Minimize to tray",
        "settings_close_ask" to "Ask me every time"
    )

    private val zh = mapOf(
        "app_name" to "Podara",
        "nav_home" to "首页",
        "nav_discover" to "发现",
        "nav_subscriptions" to "订阅",
        "nav_history" to "历史",
        "nav_settings" to "设置",
        "nav_back" to "返回",
        "home_title" to "Podara",
        "home_empty" to "还没有播客",
        "home_empty_hint" to "添加一个开始吧！",
        "home_add_podcast" to "添加播客",
        "discover_title" to "发现",
        "discover_search_hint" to "搜索播客",
        "discover_search" to "搜索",
        "discover_add" to "添加播客",
        "discover_added" to "已添加",
        "history_title" to "历史",
        "history_subtitle" to "你的收听历史",
        "history_search_placeholder" to "搜索历史记录...",
        "history_today" to "今天",
        "history_yesterday" to "昨天",
        "history_this_week" to "本周",
        "history_earlier" to "更早",
        "history_count" to "%1\$d 个节目",
        "history_empty" to "暂无历史记录",
        "history_empty_hint" to "播放过的节目会显示在这里",
        "history_clear" to "清除历史",
        "history_clear_confirm" to "确定要清除所有历史记录吗？",
        "history_clear_action" to "清除",
        "settings_title" to "设置",
        "settings_data" to "数据",
        "settings_export_opml" to "导出 OPML",
        "settings_export_opml_desc" to "将播客订阅导出为 OPML 文件",
        "settings_export" to "导出",
        "settings_import_opml" to "导入 OPML",
        "settings_import_opml_desc" to "从 OPML 文件导入播客订阅",
        "settings_import" to "导入",
        "settings_downloads" to "下载",
        "settings_download_location" to "下载位置",
        "settings_download_speed_limit" to "下载限速",
        "settings_download_speed_unlimited" to "不限速",
        "settings_download_speed_hint" to "输入每个下载任务的速度上限（0 表示不限速）：",
        "settings_download_speed_error" to "请输入非负整数",
        "settings_download_speed_unit" to "KB/s",
        "settings_change" to "更改",
        "settings_reset_default" to "恢复默认",
        "settings_language" to "语言",
        "settings_about" to "关于",
        "settings_version" to "版本 %1\$s",
        "player_play" to "播放",
        "player_pause" to "暂停",
        "player_queue" to "播放队列",
        "player_close" to "关闭",
        "player_no_playback" to "未播放",
        "player_now_playing" to "正在播放",
        "player_seek_back" to "后退",
        "player_seek_forward" to "快进",
        "player_previous" to "上一首",
        "player_next" to "下一首",
        "player_queue_count" to "播放队列 (%1\$d)",
        "player_queue_empty" to "播放队列为空",
        "player_select" to "选择",
        "player_remove" to "移除",
        "player_delete" to "删除",
        "player_sleep_timer" to "睡眠定时器",
        "player_sleep_timer_active" to "已激活：%1\$d 分钟",
        "player_cancel_timer" to "取消定时器",
        "player_minutes" to "%1\$d 分钟",
        "player_timer" to "定时器",
        "player_mute" to "静音",
        "player_unmute" to "取消静音",
        "episode_new" to "新",
        "episode_download" to "下载",
        "episode_downloaded" to "已下载",
        "episode_add_to_queue" to "添加到队列",
        "dialog_ok" to "确定",
        "dialog_cancel" to "取消",
        "dialog_close" to "关闭",
        "dialog_copy_to_clipboard" to "复制到剪贴板",
        "opml_export_title" to "导出 OPML",
        "opml_export_copy_hint" to "复制以下 OPML 内容：",
        "opml_export_copied" to "OPML 已复制到剪贴板！",
        "opml_import_title" to "导入完成",
        "opml_import_added" to "已添加：%1\$d 个播客",
        "opml_import_skipped" to "跳过（重复）：%1\$d",
        "opml_import_failed" to "失败：%1\$d",
        "opml_import_error" to "导入失败",
        "error_loading" to "加载失败：%1\$s",
        "error_adding_podcast" to "添加失败：%1\$s",
        "add_podcast_hint" to "输入播客的 RSS 订阅地址：",
        "add_podcast_rss_label" to "RSS 订阅地址",
        "add_podcast_rss_placeholder" to "https://example.com/feed.xml",
        "discover_featured" to "精选",
        "discover_latest_episode" to "最新节目",
        "discover_more" to "更多",
        "discover_new_episodes" to "热门播客",
        "discover_next" to "下一个",
        "discover_previous" to "上一个",
        "discover_results" to "搜索结果",
        "discover_search_clear" to "清除",
        "discover_search_placeholder" to "搜索播客、节目、主题...",
        "discover_show_all" to "查看全部",
        "discover_subtitle" to "精选播客，为你推荐",
        "discover_trending" to "本周热门",
        "nav_downloads" to "下载",
        "downloads_empty" to "还没有下载",
        "downloads_empty_hint" to "下载的节目会出现在这里",
        "downloads_subtitle" to "管理已下载的节目和进行中的任务",
        "downloads_in_progress" to "下载中",
        "downloads_completed" to "已完成",
        "downloads_summary_downloads" to "已下载 %1\$d 集",
        "downloads_summary_storage" to "占用空间：%1\$s",
        "downloads_summary_path" to "下载位置",
        "downloads_pause" to "暂停",
        "downloads_resume" to "恢复",
        "downloads_cancel" to "取消",
        "downloads_status_paused" to "已暂停",
        "downloads_status_failed" to "下载失败",
        "downloads_retry" to "重试",
        "downloads_delete" to "删除",
        "downloads_delete_confirm" to "确定删除此下载？",
        "downloads_delete_podcast_confirm" to "确定删除 \"%1\$s\" 下的所有下载？",
        "downloads_delete_all" to "删除全部",
        "downloads_file_missing" to "文件不存在",
        "downloads_open_folder" to "打开文件夹",
        "nav_episodes" to "节目",
        "nav_shows" to "节目",
        "player_expand" to "展开",
        "podcast_already_exists" to "播客已存在：%1\$s",
        "podcast_no_episodes" to "暂无节目",
        "podcast_retry" to "重试",
        "loading_episodes" to "正在加载节目…",
        "queue_clear" to "清空",
        "queue_title" to "即将播放",
        "search_failed" to "搜索失败：%1\$s",
        "settings_about_desc" to "Podara - 播客播放器",
        "titlebar_close" to "关闭",
        "titlebar_maximize" to "最大化",
        "titlebar_minimize" to "最小化",
        "home_edit" to "编辑",
        "home_cancel" to "取消",
        "home_select_all" to "全选",
        "home_delete_selected" to "删除选中",
        "home_selected_count" to "已选择 %1\$d 个",
        "unsubscribe" to "取消订阅",
        "unsubscribe_confirm" to "确定要取消订阅 \"%1\$s\" 吗？",
        "batch_unsubscribe" to "批量取消订阅",
        "batch_unsubscribe_confirm" to "确定要取消订阅选中的 %1\$d 个播客吗？",
        "player_follow" to "关注",
        "player_following" to "已关注",
        "player_episode_notes" to "节目笔记",
        "player_show_more" to "展开更多",
        "player_show_less" to "收起",
        "player_you_might_also_like" to "你可能也喜欢",
        "player_rewind_15" to "后退15秒",
        "player_forward_30" to "快进30秒",
        "home_subscriptions" to "我的订阅",
        "home_subscriptions_desc" to "你关注并追更的播客",
        "home_search_placeholder" to "搜索我的播客...",
        "home_manage" to "管理",
        "home_sort" to "排序",
        "home_subscription_count" to "%1\$d 个订阅",
        "home_episode_count" to "%1\$d 集",
        "home_new_badge" to "新",
        "home_new_count" to "%1\$d 新",
        "home_sort_title" to "排序方式",
        "home_sort_name_asc" to "名称 A-Z",
        "home_sort_name_desc" to "名称 Z-A",
        "home_sort_recent_update" to "最近更新",
        "home_sort_recent_listen" to "最近收听",
        // ── System Tray ──
        "tray_show" to "显示 Podara",
        "tray_hide" to "隐藏 Podara",
        "tray_play" to "播放",
        "tray_pause" to "暂停",
        "tray_previous" to "上一首",
        "tray_next" to "下一首",
        "tray_quit" to "退出",
        // ── Close Dialog ──
        "close_dialog_title" to "最小化到托盘？",
        "close_dialog_message" to "关闭窗口后你希望？",
        "close_action_quit" to "直接关闭应用",
        "close_action_minimize" to "最小化到托盘继续播放",
        "close_remember" to "记住我的选择",
        // ── Close Behavior Settings ──
        "settings_close_behavior" to "关闭行为",
        "settings_close_behavior_desc" to "选择关闭窗口时的行为",
        "settings_close_quit" to "直接关闭",
        "settings_close_minimize_tray" to "最小化到托盘",
        "settings_close_ask" to "每次询问"
    )

    private val maps = mapOf("en" to en, "zh" to zh)

    operator fun get(key: String): String {
        val map = maps[currentLanguage] ?: en
        return map[key] ?: en[key] ?: key
    }

    fun get(key: String, vararg args: Any): String {
        return String.format(get(key), *args)
    }
}
